### ISSUE TITLE
Move this into Rakuten org?

### ISSUE THREAD

**Issue by JimmyMultani** [ebates-inc/eslint-config#29]
Hey @InsaneViku, should this be moved into our Rakuten org now?

Let me know if I can help with that.

**Comment by InsaneViku** [comment]
> Hey @InsaneViku, should this be moved into our Rakuten org now?
> 
> Let me know if I can help with that.

Hey @JimmyMultani, thanks for raising this up! I'll need to check to see if we should generally move all the OSS repos under `ebates-inc` to that org. However, that org may be temporary as well - will need to confer internally on usage and migrations.

Will take that on.
